// Generated by CoffeeScript 1.6.1

app.directive('demoGreet', function($parse) {
  var directive, link_fn;
  link_fn = function(scope, l_element, attrs) {
    console.log('link', scope, l_element, attrs);
    l_element.addClass('linking');
  };
  directive = {
    link: link_fn
  };
  return directive;
});
