// Generated by CoffeeScript 1.6.1

app.directive('demoGreet', function($parse) {
  var directive, link_fn;
  link_fn = function(scope, l_element, attrs) {
    scope.$watch('name', function(name) {
      l_element.text("Hello, " + name + "!");
    });
  };
  directive = {
    link: link_fn
  };
  return directive;
});
