// Generated by CoffeeScript 1.6.1

app.directive('demoGreet', function($parse) {
  var directive, link_fn;
  link_fn = function(scope, l_element, attrs) {
    return scope.$watch(attrs.demoGreet, function(name) {
      var display_name;
      display_name = name ? name : 'Anonymous';
      l_element.text("Hello, " + display_name + "!");
      return l_element.bind('click', function() {
        return scope.$apply(function() {
          return $parse(attrs.demoGreet).assign(scope, 'Amp');
        });
      });
    });
  };
  directive = {
    link: link_fn
  };
  return directive;
});
